### ISSUE TITLE
The decoders for the Portraits and Caltran dataset are all CovDecoder84x84?

### ISSUE THREAD

**Issue by bluNeilyo** [WonderSeven/LSSAE#3]
For Portraits and Caltran dataset, you use the 84x84 patches of the images for training? Furthermore, I run your coder for these dataset, the results is far from the results presented in your paper. It may be not only the environment problem? Could you upload the code of ERM? This is the baseline, and I want to try the baseline in my computer.

**Comment by WonderSeven** [comment]
Hi, thank you for your interest in our work. 
(1) Yes, the image sizes for both Portraits and Caltran datasets are all 84x84, even though their channels are different. 
(2) The weight for the reconstruction loss term should be tuned as I use MSE loss('sum') which will sum across all pixels (line 28 in [vae_algorithms.py](https://github.com/WonderSeven/LSSAE/blob/40779fe1502e4f0ee9e5bc00550ea80ac353705f/network/vae_algorithms.py#L69), thus when you use data with a much large size (e.g. 84x84), this reconstruction term can produce an unbalanced loss value.
